- hosts: localhost
  become: true

  vars:
     username: "nawaz"
     userhome: "/home/{{ username }}"

  tasks:

    - include: tasks/configure-ubuntu.yaml
      when: ansible_facts["os_family"] == "Debian"
    - include: tasks/configure-user.yaml
    - include: tasks/configure-i3.yaml

