- name: i3 Configuration - Create .i3 directory
  become_user: "{{ username }}"
  file:
    path: "{{ userhome }}/.i3"
    state: directory

- name: i3 Configuration - Copy i3 config
  become_user: "{{ username }}"
  copy:
    src: "files/i3/config"
    dest: "{{ userhome }}/.i3/config"


- name: i3 Configuration - Create compton directory
  become_user: "{{ username }}"
  file:
    path: "{{ userhome }}/.config/compton"
    state: directory

- name: i3 Configuration - Copy compton config
  become_user: "{{ username }}"
  copy:
    src: "files/config/compton.conf"
    dest: "{{ userhome }}/.config/compton/compton.conf"


- name: i3 Configuration - Create dunst directory
  become_user: "{{ username }}"
  file:
    path: "{{ userhome }}/.config/dunst"
    state: directory

- name: i3 Configuration - Copy dunst config
  become_user: "{{ username }}"
  copy:
    src: "files/config/dunst/dunstrc"
    dest: "{{ userhome }}/.config/dunst/dunstrc"


- name: i3 Configuration - Create i3blocks directory
  become_user: "{{ username }}"
  file:
    path: "{{ userhome }}/.config/i3blocks"
    state: directory
    
- name: i3 Configuration - Copy i3blocks config
  become_user: "{{ username }}"
  copy:
    src: "files/config/i3blocks/config"
    dest: "{{ userhome }}/.config/i3blocks/config"
    
    
- name: i3 Configuration - Create rofi directory
  become_user: "{{ username }}"
  file:
    path: "{{ userhome }}/.config/rofi"
    state: directory

- name: i3 Configuration - Copy rofi config
  become_user: "{{ username }}"
  copy:
    src: "files/config/rofi/config"
    dest: "{{ userhome }}/.config/rofi/config"


- name: i3 Configuration - Create conky directory
  become_user: "{{ username }}"
  file:
    path: "{{ userhome }}/.config/conky"
    state: directory

- name: i3 Configuration - Copy conky scripts
  become_user: "{{ username }}"
  copy:
    src: files/conky/
    dest: "{{ userhome }}/.config/conky/"
    mode: "0755"


- name: i3 Configuration - Create polybar directory
  become_user: "{{ username }}"
  file:
    path: "{{ userhome }}/.config/polybar"
    state: directory

- name: i3 Configuration - Copy polybar scripts
  become_user: "{{ username }}"
  copy:
    src: files/config/polybar
    dest: "{{ userhome }}/.config/"
    mode: "0755"


- name: i3 Configuration - Create .fonts directory
  become_user: "{{ username }}"
  file:
    path: "{{ userhome }}/.fonts"
    state: directory

- name: i3 Configuration - Copy Source Code Pro Fonts
  become_user: "{{ username }}"
  copy:
    src: files/fonts/
    dest: "{{ userhome }}/.fonts/"
    mode: "0755"
    
- name: i3 Configuration - Copy blurlock script
  copy:
    src: files/blurlock
    dest: /usr/bin/blurlock
    mode: '0777'

- name: i3 Configuration - Copy i3exit script
  copy:
    src: files/i3exit
    dest: /usr/bin/i3exit
    mode: '0777'

- name: i3 Configuration - Copy i3blocks scripts
  become_user: "{{ username }}"
  copy:
    src: files/i3block-scripts/
    dest: "{{ userhome }}/opt/scripts/myi3blocks/"
    mode: "0755"
